image: maven-3.9.9-openjdk-1.21

cache:
  key: mvn-cache
  paths:
    - .m2

variables:
  MAVEN_USER_HOME: $CI_PROJECT_DIR/.m2
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -U -DinstallAtEnd=true -DdeployAtEnd=true -DgitLab=true -Dci-pipeline=true"


stages:
  - verify

verify-job:
  stage: verify
  script:
    - mvn $MAVEN_CLI_OPTS clean verify -Pdoc,src
  only:
    refs:
      - merge_requests
