<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.lemon-ant.jharmonizer.it</groupId>
    <artifactId>reorder-basic-it</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>IT: reorder-basic</name>

    <build>
        <plugins>
            <plugin>
                <groupId>io.github.lemon-ant.jharmonizer</groupId>
                <artifactId>jharmonizer-maven-plugin</artifactId>
                <version>@project.version@</version>
                <executions>
                    <execution>
                        <id>reorder-sources</id>
                        <goals>
                            <goal>reorder</goal>
                        </goals>
                        <phase>process-sources</phase>
                        <configuration>
                            <backupsEnabled>false</backupsEnabled>
                            <printProcessingStatistics>false</printProcessingStatistics>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
