type-sort:
 - name: Test classes
   match:
    - "@Test"
    - "@ExtendWith"
    - class-name~".*Test$"
   groups:
    - name: JUnit setup
      separator: header
      select: annotation:["@BeforeEach", "@BeforeAll"]
      order: preserve

    - name: Test methods
      separator: header
      select: annotation:@Test
      order: alpha

    - name: JUnit teardown
      separator: header
      select: annotation:["@AfterEach", "@AfterAll"]
      order: preserve

    - name: Utility overrides
      separator: none
      select: annotation:@Override
      order: preserve

    - name: Object methods
      separator: none
      select: name=toString()
      order: preserve

    - name: Getters
      separator: none
      select: name~/get.+/
      order: alpha

    - name: Rest
      separator: none
      select: rest
      order: preserve

 - name: Utility classes
   match:
    - modifiers=final
    - modifiers=static
    - class-name~".*Util$"
   groups:
    - name: Static fields
      separator: header
      select:
       type: field
       modifiers: static
      order: alpha

    - name: Instance fields
      separator: header
      select:
       type: field
       modifiers: instance
      order: alpha

    - name: Getters
      separator: none
      select: name~/get.+/
      order: alpha

    - name: Setters
      separator: none
      select: name~/set.+/
      order: alpha

 - name: DTO classes
   match:
    - class-name~".*Dto$"
   groups:
    - name: Fields
      separator: header
      select: type:field
      order: alpha

    - name: Methods
      separator: header
      select: type:method
      groups:
       - name: Accessors
         separator: none
         select: name:~^(get|is).+$
         group-with:
          - select: name:~^set.+$
         order: alpha

       - name: Other methods
         separator: none
         select: rest
         order: preserve
      rest: alpha

 - name: Default rule
   groups:
    - name: Public static fields
      separator: header
      select:
       type: field
       modifiers: [static, public]
      order: alpha

    - name: Private static fields
      separator: none
      select:
       type: field
       modifiers: [static, private]
      order: preserve

    - name: Public instance fields
      separator: line
      select:
       type: field
       modifiers: [instance, public]
      order: alpha

    - name: Private instance fields
      separator: none
      select:
       type: field
       modifiers: [instance, private]
      order: preserve

    - name: Overrides
      separator: none
      select: annotation:@Override
      order: preserve

    - name: Object methods
      separator: none
      select: name=toString()
      order: preserve

    - name: Default
      separator: none
      select: rest
      order: alpha
