java-file:
 main-type-first: true
 type-order:
  - public-class
  - interface
  - [class, records]
  - enum
 sort: alpha

selector-aliases:
 object-methods: '~^(toString\\(\\)|equals\\(\\)|hashCode\\(\\)|clone\\(\\)|finalize\\(\\))$'
 junit-init:
  - '@BeforeEach'
  - '@BeforeAll'
 junit-cleanup:
  - '@AfterEach'
  - '@AfterAll'
 test-class: "~.*Test$"

type-sort:
 test:
  match: test-class
  sort:
   method:
    junit-init: orig
    '@Test': alpha
    junit-cleanup: orig
    rest: orig

 utility:
  match:
   - [final, static]
   - "~.*Utils?$"
  sort:
   field:
    static: alpha
    instance: alpha
   method: alpha

 dto:
  match: [final, "~.*Dto$"]
  behavior:
   keepAccessorsTogether: true
  sort:
   field:
    instance: alpha
   method: alpha

 default:
  behavior:
   keepAccessorsTogether: true
  sort:
   field:
    static:
     public: alpha
     private: orig
    instance:
     public: alpha
     private: orig
   method:
    '@Override': orig
    object-methods: orig
