formatting:
  fix-imports: true
  formatter-style: PALANTIR # NONE, AOSP, GOOGLE, PALANTIR

backups-enabled: true

header-line:
  character: '-'
  left-padding: 3

top-level-types-ordering:
  main-type-first: true
  type-groups:
    - [ class, record ]
    - interface
    - enum
    - annotation
  sort-keys: [ visibility-desc, alpha ]

type-members-ordering:
  - name: Test Classes
    includes:
      - [ class, '@~.*Test$' ]
      - [ class, '@ExtendWith' ]
      - [ class, '@RunWith' ]
      - [ class, ~.*Test$ ]
    sort-keys: alpha, signature
    groups:
      - name: JUnit Fields
        separator: new-line
        sort-keys: [ visibility-desc, alpha ]
        includes: field
        groups:
          - name: JUnit Constants
            separator: new-line
            sort-keys: [ visibility-desc, alpha ]
            includes: [ static, final ]
          - name: JUnit Static fields
            separator: new-line
            sort-keys: [ visibility-desc, alpha ]
            includes: static

      - name: JUnit Methods
        separator: new-line
        sort-keys: alpha, signature
        includes: method
        groups:
          - name: JUnit Setup Methods
            separator: header
            sort-keys: preserve
            includes:
              - '@BeforeEach'
              - '@BeforeAll'

          - name: JUnit Test Methods
            separator: header
            sort-keys: alpha
            includes: '@Test'

          - name: JUnit Teardown Methods
            separator: header
            sort-keys: preserve
            includes:
              - '@AfterEach'
              - '@AfterAll'

          - name: Utility Methods
            separator: header
            includes: static
            sort-keys: alpha, signature

      - name: JUnit Test Configuration
        separator: new-line
        sort-keys: alpha
        includes:
          - [ static, class, '@TestConfiguration' ]


  - name: DTO and Entities
    includes:
      - ~.*(Dto|DTO)$
      - ~.*Entity$
      - '@Value'
      - '@Data'
      - '@Entity'
      - '@MappedSuperclass'
      - '@Embeddable'
      - '@ConfigurationProperties'
      - '@Document'
    sort-keys: [ visibility-desc, alpha, signature ]
    groups:
      - name: Serializable UID
        separator: new-line
        sort-keys: preserve
        includes: [ field, static, final, =serialVersionUID ]

      - name: Fields
        separator: new-line
        sort-keys: [ visibility-desc, alpha ]
        includes: field
        groups:
          - name: Constants
            separator: new-line
            sort-keys: [ visibility-desc, alpha ]
            includes: [ static, final ]
            groups:
              - name: Public Constants
                separator: new-line
                sort-keys: alpha
                includes: public
              - name: Protected Constants
                separator: new-line
                sort-keys: alpha
                includes: protected
              - name: Package-Private Constants
                separator: new-line
                sort-keys: alpha
                includes: package-private
              - name: Private Constants
                separator: new-line
                sort-keys: alpha
                includes: private

          - name: Static Fields
            separator: new-line
            sort-keys: [ visibility-desc, alpha ]
            includes: static

          - name: Final Instance Fields
            separator: new-line
            sort-keys: [ visibility-desc, alpha ]
            includes: final

      - name: Static Initializer Blocks
        separator: none
        sort-keys: preserve
        includes: [ static, initializer ]

      - name: Static Methods
        separator: none
        sort-keys: [ visibility-desc, alpha, signature ]
        includes: [ static, method ]

      - name: Instance Initializer Blocks
        separator: none
        sort-keys: preserve
        includes: [ instance, initializer ]

      - name: Constructors
        separator: none
        sort-keys: [ visibility-desc, alpha, signature ]
        includes: constructor

      - name: Accessor Methods
        separator: none
        keepAccessorsTogether: true
        sort-keys: [ visibility-desc, alpha, signature ]
        includes: [ instance, method, ~^(get|set|is|has).+$ ]

      - name: Instance Methods
        separator: none
        sort-keys: [ visibility-desc, alpha, signature ]
        includes: [ instance, method ]
        excludes:
          - [ instance, method, =toString ]
          - [ instance, method, =equals ]
          - [ instance, method, =hashCode ]
          - [ instance, method, =clone ]

      - name: Basic Object Methods
        sort-keys: preserve
        includes:
          - [ instance, method, =toString ]
          - [ instance, method, =equals ]
          - [ instance, method, =hashCode ]
          - [ instance, method, =clone ]

  - name: Default Rule
    includes: ~.*
    sort-keys: [ visibility-desc, alpha, signature ] # For subtypes
    groups:
      - name: Serializable UID
        separator: new-line
        sort-keys: preserve
        includes: [ field, static, final, =serialVersionUID ]

      - name: Logger
        separator: new-line
        sort-keys: preserve
        includes:
          - [ field, static, final, '~(?i)(log|.*logger)$' ]

      - name: Fields
        separator: new-line
        sort-keys: [ visibility-desc, alpha ]
        includes: field
        groups:
          - name: Constants
            separator: new-line
            sort-keys: [ visibility-desc, alpha ]
            includes: [ static, final ]
            groups:
              - name: Public Constants
                separator: new-line
                sort-keys: alpha
                includes: public
              - name: Protected Constants
                separator: new-line
                sort-keys: alpha
                includes: protected
              - name: Package-Private Constants
                separator: new-line
                sort-keys: alpha
                includes: package-private
              - name: Private Constants
                separator: new-line
                sort-keys: alpha
                includes: private

          - name: Static Fields
            separator: new-line
            sort-keys: [ visibility-desc, alpha ]
            includes: static

          - name: Final Instance Fields
            separator: new-line
            sort-keys: [ visibility-desc, alpha ]
            includes: final

      - name: Static Initializer Blocks
        separator: none
        sort-keys: preserve
        includes: [ static, initializer ]

      - name: Static Methods
        separator: none
        sort-keys: [ visibility-desc, alpha, signature ]
        includes: [ static, method ]

      - name: Instance Initializer Blocks
        separator: none
        sort-keys: preserve
        includes: [ instance, initializer ]

      - name: Constructors
        separator: none
        sort-keys: [ visibility-desc, alpha, signature ]
        includes: constructor

      - name: Instance Methods
        separator: none
        sort-keys: [ visibility-desc, alpha, signature ]
        includes: [ instance, method ]
        excludes:
          - [ instance, method, =toString ]
          - [ instance, method, =equals ]
          - [ instance, method, =hashCode ]
          - [ instance, method, =clone ]

      - name: Basic Object Methods
        separator: none
        sort-keys: preserve
        includes:
          - [ instance, method, =toString ]
          - [ instance, method, =equals ]
          - [ instance, method, =hashCode ]
          - [ instance, method, =clone ]

      - name: Classes & Records
        separator: new-line
        sort-keys: [ alpha ]
        includes: [ class, record ]

      - name: Interfaces
        separator: new-line
        sort-keys: [ alpha ]
        includes: [ interface ]

      - name: Enums
        separator: new-line
        sort-keys: [ alpha ]
        includes: [ enum ]

      - name: Annotations
        separator: new-line
        sort-keys: [ alpha ]
        includes: [ annotation ]
