<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.lemon-ant.jharmonizer.it</groupId>
    <artifactId>check-excludes-it</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>IT: check-excludes</name>

    <repositories>
        <repository>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
            <id>github</id>
            <name>GitHub Packages (lemon-ant)</name>
            <url>https://maven.pkg.github.com/lemon-ant/glob-path-finder</url>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <groupId>io.github.lemon-ant.jharmonizer</groupId>
                <artifactId>jharmonizer-maven-plugin</artifactId>
                <version>@project.version@</version>
                <executions>
                    <execution>
                        <id>check-sources</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>verify</phase>
                        <configuration>
                            <excludes>
                                <exclude>**/ViolationSample.java</exclude>
                            </excludes>
                            <printProcessingStatistics>false</printProcessingStatistics>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
